name: Docker Image CI for GHCR

on:
    push

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build and push the image
              run: |
                docker login --username khbhatia --password ${{secrets.SECRET_TOKEN}} ghcr.io
                docker build -t ghcr.io/khbhatia/arithmetic-service:latest --file Dockerfile .  
                docker push ghcr.io/khbhatia/arithmetic-service:latest
